"""added fallback otp

Revision ID: a052714d21a1
Revises: 16e1f855242d
Create Date: 2025-02-05 23:06:45.999019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a052714d21a1'
down_revision = '16e1f855242d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fallback_otp_secret', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fallback_otp_secret')

    # ### end Alembic commands ###
